name: Try JamesIves/github-pages-deploy-action
on: { workflow_dispatch, push: { paths-ignore: [ '**', '!.github/workflows/deploy_aka_JamesIves.yml' ] } }
permissions:
  contents: write # read for "actions/checkout@v3" when GITHUB_TOKEN, write for "JamesIves/github-pages-deploy-action"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.ACCESS_TO_READ_ARTIFACT_FROM_ALL_REPOS }}
          repo: Alex0vSky/HelloWinHlsl
          workflow: qa-StaticAnalysis-CodeMetrics.yml
          name: artifact-qa-StaticAnalysis_CodeMetrics
          search_artifacts: true
          path: HelloWinHlsl
      - name: Mark
        run: |
          echo "'${{github.workflow}}', '${{github.run_number}}.${{github.run_attempt}}'" > HelloWinHlsl/from_action.txt
          ls .
          ls HelloWinHlsl
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: HelloWinHlsl
          target-folder: HelloWinHlsl
          clean: true
