name: Try JamesIves/github-pages-deploy-action
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read # for "dawidd6/action-download-artifact@v2"
      contents: write # read for "actions/checkout@v3" when GITHUB_TOKEN, write for "JamesIves/github-pages-deploy-action"
    steps:
      - name: Disclosure token
        run: | 
          echo "secret0: " ${{secrets.GITHUB_TOKEN}}
          echo "secret1: " ${{secrets.PAT_TINYSYNAPTICSSCROLL}}
          echo "secret2: " ${{secrets.PAT_CLASSIC_TINYSYNAPTICSSCROLL}}
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        env:
          GITHUB_TOKEN: ${{secrets.PAT_TINYSYNAPTICSSCROLL}}
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: googletest.yml
          name: my-artifact
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gtest_report\out
