name: Try JamesIves/github-pages-deploy-action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read # for "dawidd6/action-download-artifact@v2"
      contents: write # read for "actions/checkout@v3" when GITHUB_TOKEN, write for "JamesIves/github-pages-deploy-action"
    steps:
      - name: Download artifact
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TINYSYNAPTICSSCROLL }}
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: googletest.yml
          name: my-artifact
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure

      - name: Download artifact
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_CLASSIC_TINYSYNAPTICSSCROLL }}
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: googletest.yml
          name: my-artifact
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure

      - name: Download artifact
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TINYSYNAPTICSSCROLL1 }}
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: googletest.yml
          name: my-artifact
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure

      - name: Download artifact
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TINYSYNAPTICSSCROLL2 }}
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: googletest.yml
          name: my-artifact
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure

      # - name: Deploy 🚀
        # uses: JamesIves/github-pages-deploy-action@v4
        # with:
          # folder: gtest_report\out
