name: Try JamesIves/github-pages-deploy-action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # read for "actions/checkout@v3" when GITHUB_TOKEN, write for "JamesIves/github-pages-deploy-action"
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.FROM_USER_SETTINGS__PAT_CLASSIC_TINYSYNAPTICSSCROLL }}
          workflow: googletest.yml
          name: artifact-all-tests-builded
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure
