name: Try JamesIves/github-pages-deploy-action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read # for "dawidd6/action-download-artifact@v2"
      contents: write # read for "actions/checkout@v3" when GITHUB_TOKEN, write for "JamesIves/github-pages-deploy-action"
    steps:

      - uses: actions/checkout@v3
        continue-on-error: true
        with:
            repository: Alexovsky5/turbo-octo-adventure
            token: ${{ secrets.PAT_TINYSYNAPTICSSCROLL }}

      - uses: actions/checkout@v3
        continue-on-error: true
        with:
            repository: Alexovsky5/turbo-octo-adventure
            token: ${{ secrets.PAT_CLASSIC_TINYSYNAPTICSSCROLL }}

      - uses: actions/checkout@v3
        continue-on-error: true
        with:
            repository: Alexovsky5/turbo-octo-adventure
            token: ${ PAT_TINYSYNAPTICSSCROLL }

      - uses: actions/checkout@v3
        continue-on-error: true
        with:
            repository: Alexovsky5/turbo-octo-adventure
            token: ${ PAT_CLASSIC_TINYSYNAPTICSSCROLL }

      - uses: actions/checkout@v3
        continue-on-error: true
        with:
            repository: Alexovsky5/turbo-octo-adventure
            token: $PAT_TINYSYNAPTICSSCROLL

      - uses: actions/checkout@v3
        continue-on-error: true
        with:
            repository: Alexovsky5/turbo-octo-adventure
            token: $PAT_CLASSIC_TINYSYNAPTICSSCROLL
