name: Try standart (Beta) actions/deploy-pages
on: [push,workflow_dispatch]
jobs:
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.FROM_USER_SETTINGS__PAT_CLASSIC_TINYSYNAPTICSSCROLL }}
          workflow: googletest.yml
          name: artifact-gtest-report
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure
      - name: Renaming
        run: |
          mv -v gtest_report/out/gtest_report.html gtest_report/out/index.html
          echo 123 123 > gtest_report/out/test.txt

      - uses: actions/upload-pages-artifact@v1
        with:
          path: gtest_report/out
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
