name: Try JamesIves/github-pages-deploy-action 2
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        env:
          GITHUB_TOKEN: ${PAT_TINYSYNAPTICSSCROLL}
        with:
          GITHUB_TOKEN: ${PAT_TINYSYNAPTICSSCROLL}
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: googletest.yml
          name: artifact-all-tests-builded
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure
