name: Try JamesIves/github-pages-deploy-action
on: [push,workflow_dispatch]
permissions:
  contents: write # read for "actions/checkout@v3" when GITHUB_TOKEN, write for "JamesIves/github-pages-deploy-action"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.FROM_USER_SETTINGS__PAT_CLASSIC_TINYSYNAPTICSSCROLL }}
          workflow: googletest.yml
          name: my-artifact
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure
      - name: Renaming
        run: |
          mv -v gtest_report/out/gtest_report.html gtest_report/out/index.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: gtest_report/out
