name: Try JamesIves/github-pages-deploy-action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: $PAT_TINYSYNAPTICSSCROLL
          workflow: googletest.yml
          name: artifact-all-tests-builded
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure

      - name: Download artifact
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        env:
          GITHUB_TOKEN: ${PAT_TINYSYNAPTICSSCROLL}
        with:
          github_token: $GITHUB_TOKEN
          workflow: googletest.yml
          name: artifact-all-tests-builded
          search_artifacts: true
          repo: Alexovsky5/turbo-octo-adventure

      - uses: actions/checkout@v3
        continue-on-error: true
        with:
            repository: Alexovsky5/turbo-octo-adventure
            token: ${PAT_TINYSYNAPTICSSCROLL}
