name: Publish GitHubPages by event
on: { repository_dispatch: { types: [a0s_event_public_pages] } }
permissions:
  contents: write # write for "JamesIves/github-pages-deploy-action"
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
# Has no configuration
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read event client_payload
        run: |
          echo ${{ github.event.client_payload.repo }}
          echo ${{ github.event.client_payload.workflow }}
          echo ${{ github.event.client_payload.artifact }}
          echo ${{ github.event.client_payload.project }}
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.ACCESS_TO_READ_ARTIFACT_FROM_ALL_REPOS }}
          repo: ${{ github.event.client_payload.repo }}
          workflow: ${{ github.event.client_payload.workflow }}
          name: ${{ github.event.client_payload.artifact }}
          search_artifacts: true
          path: ${{ github.event.client_payload.project }}
      - name: Mark
        run: echo "'${{github.workflow}}', '${{github.run_number}}.${{github.run_attempt}}'" > ${{ github.event.client_payload.project }}/from_action.txt
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: ${{ github.event.client_payload.project }}
          target-folder: ${{ github.event.client_payload.project }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
