name: Public GitHubPages by event
on: { repository_dispatch: { types: [a0s_event_public_pages] } }
permissions:
  contents: write # read for "actions/checkout@v3" when GITHUB_TOKEN, write for "JamesIves/github-pages-deploy-action"
# Configuration no
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read event client_payload
        run: |
          echo ${{ github.event.client_payload.project }}
          echo ${{ github.event.client_payload.repo }}
          echo ${{ github.event.client_payload.workflow }}
          echo ${{ github.event.client_payload.artifact }}
